services:
  wis:
    build: 
      context: wis
    ports:
      - 8014:8014/tcp
      - 8014:8014/udp
  md:
    build: 
      context: md
    ports:
      - 8020:8020/tcp
      - 8020:8020/udp
    depends_on: 
      - wis
    