services:
  wenv:
    image: docker.io/natbodocker/virtualrobotdisi23:1.0
    ports:
      - 8090:8090
      - 8091:8091/tcp
      - 8091:8091/udp
  basicrobot24:
    image: docker.io/natbodocker/basicrobot24:1.0
    #image: basicrobot24:1.0
    ports:
      - 8020:8020/tcp
      - 8020:8020/udp
    depends_on:
      - wenv
